import React, { useEffect, useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { getAccessToken } from "../api/client";
import { ScoreCard, type EvaluationScores } from "../components/ScoreCard";

type Turn = { id: string; role: "USER" | "ASSISTANT"; content: string; metadata?: { evaluation?: EvaluationScores } };
type Session = { id: string; mode: string; difficulty: string; targetCompany: string | null; turns: Turn[] };
const API_BASE = import.meta.env.VITE_API_URL || "http://localhost:4000";
const starterQuestion = (mode: string) => mode === "Behavioural" ? "Tell me about a time you handled a difficult challenge with your team. What did you do, and what was the result?" : mode === "Case Study" ? "How would you approach improving the activation rate for a new product?" : "Walk me through how you would design a scalable URL-shortening service.";

export const InterviewRoom: React.FC = () => {
  const { id } = useParams(); const [session, setSession] = useState<Session | null>(null); const [answer, setAnswer] = useState(""); const [streamingQuestion, setStreamingQuestion] = useState(""); const [isStreaming, setIsStreaming] = useState(false); const [error, setError] = useState<string | null>(null); const [scores, setScores] = useState<EvaluationScores | null>(null);
  useEffect(() => { (async () => { try { const response = await fetch(`${API_BASE}/api/sessions/${id}`, { headers: { Authorization: `Bearer ${getAccessToken()}` }, credentials: "include" }); const data = await response.json(); if (!response.ok) throw new Error(data.error?.message || "Unable to load session"); setSession(data.session); const lastUserTurn = [...data.session.turns].reverse().find((turn: Turn) => turn.role === "USER"); if (lastUserTurn?.metadata?.evaluation) setScores(lastUserTurn.metadata.evaluation); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Unable to load session"); } })(); }, [id]);
  const currentQuestion = useMemo(() => streamingQuestion || [...(session?.turns || [])].reverse().find((turn) => turn.role === "ASSISTANT")?.content || (session ? starterQuestion(session.mode) : ""), [session, streamingQuestion]);
  const submitAnswer = async (event: React.FormEvent) => { event.preventDefault(); if (!answer.trim() || !id || isStreaming) return; setError(null); setScores(null); setStreamingQuestion(""); setIsStreaming(true); try { const response = await fetch(`${API_BASE}/api/sessions/${id}/turns/stream`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${getAccessToken()}` }, credentials: "include", body: JSON.stringify({ answer }) }); if (!response.ok || !response.body) { const data = await response.json().catch(() => ({})); throw new Error(data.error?.message || "Unable to submit answer"); } const reader = response.body.getReader(); const decoder = new TextDecoder(); let buffer = ""; while (true) { const { done, value } = await reader.read(); if (done) break; buffer += decoder.decode(value, { stream: true }); const messages = buffer.split("\n\n"); buffer = messages.pop() || ""; for (const message of messages) { const eventLine = message.split("\n").find((line) => line.startsWith("event:")); const dataLine = message.split("\n").find((line) => line.startsWith("data:")); const eventName = eventLine?.slice(6).trim(); if (!dataLine) continue; const payload = JSON.parse(dataLine.slice(5).trim()); if (eventName === "delta") setStreamingQuestion((current) => current + payload.content); if (eventName === "done") { setSession((current) => current ? { ...current, turns: [...current.turns, payload.turn, payload.nextQuestion] } : current); if (payload.turn.metadata?.evaluation) setScores(payload.turn.metadata.evaluation); setAnswer(""); } if (eventName === "error") throw new Error(payload.message || "Interview stream failed"); } } } catch (submitError) { setError(submitError instanceof Error ? submitError.message : "Unable to submit answer"); } finally { setIsStreaming(false); } };
  if (!session && !error) return <div className="room-page room-loading">Loading your interview room...</div>;
  if (!session) return <div className="room-page room-loading"><p>{error}</p><Link to="/">Return to dashboard</Link></div>;
  return <div className="room-page"><header className="room-header"><Link to="/" className="back-link">← Dashboard</Link><div><strong>{session.mode} interview</strong><span>{session.difficulty.toLowerCase()} difficulty{session.targetCompany && ` · ${session.targetCompany}`}</span></div></header><main className="room-layout"><section className="interview-panel"><p className="section-kicker">Interviewer question</p><h1>{currentQuestion || "Preparing your next question..."}</h1>{isStreaming && <span className="streaming-indicator">Generating response...</span>}<form onSubmit={submitAnswer}><label htmlFor="answer">Your answer</label><textarea id="answer" value={answer} onChange={(event) => setAnswer(event.target.value)} placeholder="Think aloud, explain your reasoning, and mention any trade-offs…" disabled={isStreaming} required /><div className="answer-actions"><span>{answer.trim().split(/\s+/).filter(Boolean).length} words</span><button className="primary-action" disabled={isStreaming || !answer.trim()}>{isStreaming ? "Interviewing…" : "Submit answer"}</button></div></form>{error && <p className="room-error">{error}</p>}</section>{scores ? <ScoreCard scores={scores} /> : <aside className="room-tip"><p className="section-kicker">Interview tip</p><h3>Make your thinking visible</h3><p>Lead with your approach, then explain trade-offs and edge cases. This gives the interviewer a clearer signal.</p></aside>}</main></div>;
};
